### ISSUE TITLE
部署成功了，说下过程遇到的问题

### ISSUE THREAD

**Issue by DSbajRv5Ol4X** [gstok/qqgroup-visualization#7]
我用的是:QQ群关系数据客查询（表格版）
部署完成并执行npm run start之后出现
Your application is running here: http://localhost:8080
按理来说把localhost改成IP就可以访问了，但是浏览器打开却没反应

最后的解决方法是进去config目录，把index.js文件里面的
host: 'localhost'
改成
host: '你的IP'

https://blog.csdn.net/qq_31113123/article/details/81705421
前端部署成功，数据可正常连接但是搜索的时候提示"网络请求发生错误！"
前端centos 6系统、数据库用的是远程连接

**Comment by XiLingHost** [comment]
进config里把host改成0.0.0.0好像就能用任何可达的ip地址/域名访问了

**Comment by DSbajRv5Ol4X** [comment]
![qq 20181018014157](https://user-images.githubusercontent.com/16274567/47105729-57c0e280-d277-11e8-8ab9-73ff9483e5ef.jpg)
